[tool.poetry]
name = "pttautosign"
version = "1.0.2"
description = "PTT auto sign-in tool with Telegram notifications"
authors = ["crazycat836 <crazycat836@gmail.com>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.11"
pyptt = "^1.2.0"
python-dotenv = "^1.0.1"

[tool.poetry.group.dev.dependencies]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
addopts = "--no-bytecode"
